[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_test_utils"
resolver = "2"
version = "0.12.0"

[dependencies]
namada_core = { path = "../core", features = ["testing"]}
git2 = "0.13.20"